#!/usr/bin/env python

import logging
import sys

sys.path.append('/usr/share/mfgames-writing')
sys.path.append('/usr/local/share/mfgames-writing')

import tools
import writing.opf.cover
import writing.opf.dc
import writing.opf.guide
import writing.opf.manifest
import writing.opf.spine
import writing.opf.toc


def do_opf_tool(arguments):
    tools.run_tool(
        "Query and manipulate OPF files.",
        arguments,
        {
            'cover-get': writing.opf.cover.CoverGetProcess(),
            #'cover-set': writing.opf.cover.CoverSetProcess(),
            #'dc-add': writing.opf.dc.DublicCoreAddProcess(),
            'dc-list': writing.opf.dc.DublinCoreListProcess(),
            #'dc-remove': writing.opf.dc.DublinCoreRemoveProcess(),
            #'dc-set': writing.opf.dc.DublinCoreSetProcess(),
            'guide-list': writing.opf.guide.GuideListProcess(),
            #'manifest-add': writing.opf.manifest.ManifestAddProcess(),
            'manifest-list': writing.opf.manifest.ManifestListProcess(),
            #'manifest-remove': writing.opf.manifest.ManifestRemoveProcess(),
            #'manifest-set': writing.opf.manifest.ManifestSetProcess(),
            'spine-list': writing.opf.spine.SpineListProcess(),
            #'spine-add': writing.opf.spine.SpineAddProcess(),
            #'spine-remove': writing.opf.spine.SpineRemoveProcess(),
            'toc-get': writing.opf.toc.TocGetProcess(),
            #'toc-set': writing.opf.toc.TocSetprocess(),
        })


if __name__ == "__main__":
    do_opf_tool(sys.argv[1:])
