#!/usr/bin/env python

import logging
import sys

sys.path.append('/usr/share/mfgames-writing')
sys.path.append('/usr/local/share/mfgames-writing')

import tools
import writing.docbook.count
import writing.docbook.info
import writing.docbook.text


def do_docbook_tool(arguments):
    tools.run_tool(
        "Manipulate and convert DocBook 5 files.",
        arguments,
        {
            'bbcode': writing.docbook.text.ConvertToBBCodeFilesProcess(),
            'count': writing.docbook.count.CountProcess(),
            'creole': writing.docbook.text.ConvertToCreoleFilesProcess(),
            'subjectsets':
                writing.docbook.info.ExtractSubjectsetsProcess(),
        })


if __name__ == "__main__":
    do_docbook_tool(sys.argv[1:])
