#!/usr/bin/env python


import logging
import mfgames_tools
import mfgames_writing.ncx.author
import mfgames_writing.ncx.meta
import mfgames_writing.ncx.nav
import mfgames_writing.ncx.title
import sys


def do_ncx_tool(arguments):
    mfgames_tools.run_tool(
        "Query and manipulate NCX files.",
        arguments,
        {
            'author-get': mfgames_writing.ncx.author.AuthorGetProcess(),
            'author-set': mfgames_writing.ncx.author.AuthorSetProcess(),
            'format': mfgames_writing.ncx.FormatFileProcess(),
            'meta-list': mfgames_writing.ncx.meta.MetaListProcess(),
            'meta-remove': mfgames_writing.ncx.meta.MetaRemoveProcess(),
            'meta-set': mfgames_writing.ncx.meta.MetaSetProcess(),
            'nav-append': mfgames_writing.ncx.nav.NavAppendProcess(),
            'nav-insert': mfgames_writing.ncx.nav.NavInsertProcess(),
            'nav-list': mfgames_writing.ncx.nav.NavListProcess(),
            'nav-remove': mfgames_writing.ncx.nav.NavRemoveProcess(),
            'title-get': mfgames_writing.ncx.title.TitleGetProcess(),
            'title-set': mfgames_writing.ncx.title.TitleSetProcess(),
        })


if __name__ == "__main__":
    do_ncx_tool(sys.argv[1:])
