#!/usr/bin/env python

import logging
import sys

sys.path.append('/usr/share/mfgames-writing')
sys.path.append('/usr/local/share/mfgames-writing')

import tools
import writing.docbook.text


def do_docbook_tool(arguments):
    tools.run_tool(
        "Manipulate and convert DocBook 5 files.",
        arguments,
        {
            'bbcode': writing.docbook.text.ConvertToBBCodeFilesProcess(),
            'creole': writing.docbook.text.ConvertToCreoleFilesProcess(),
            'extract-subjectsets':
                writing.docbook.scan.ExtractSubjectsetsProcess(),
        })


if __name__ == "__main__":
    do_docbook_tool(sys.argv[1:])
