#!/usr/bin/env python

import logging
import sys
import mfgames_tools
import mfgames_writing.docbook.wordpress


reload(sys);
sys.setdefaultencoding('utf-8')


def do_docbook_wordpress_tool(arguments):
    processes = {
        'upload': mfgames_writing.docbook.wordpress.UploadFilesProcess(),
        }

    mfgames_tools.run_tool(
        "Manages WordPress sites that use DocBook files.",
        arguments,
        processes,
        config_id="mfgames-docbook-wordpress")


if __name__ == "__main__":
    do_docbook_wordpress_tool(sys.argv[1:])
