#!/usr/bin/env python

import logging
import mfgames_tools
import mfgames_writing.opf.cover
import mfgames_writing.opf.dc
import mfgames_writing.opf.guide
import mfgames_writing.opf.manifest
import mfgames_writing.opf.spine
import mfgames_writing.opf.toc
import mfgames_writing.opf.uid
import sys


def do_opf_tool(arguments):
    mfgames_tools.run_tool(
        "Query and manipulate OPF files.",
        arguments,
        {
            'cover-get': mfgames_writing.opf.cover.CoverGetProcess(),
            'cover-set': mfgames_writing.opf.cover.CoverSetProcess(),
            'dc-list': mfgames_writing.opf.dc.DublinCoreListProcess(),
            'dc-remove': mfgames_writing.opf.dc.DublinCoreRemoveProcess(),
            'dc-set': mfgames_writing.opf.dc.DublinCoreSetProcess(),
            'guide-list': mfgames_writing.opf.guide.GuideListProcess(),
            'guide-remove': mfgames_writing.opf.guide.GuideRemoveProcess(),
            'guide-set': mfgames_writing.opf.guide.GuideSetProcess(),
            'manifest-list': mfgames_writing.opf.manifest.ManifestListProcess(),
            'manifest-remove': mfgames_writing.opf.manifest.ManifestRemoveProcess(),
            'manifest-set': mfgames_writing.opf.manifest.ManifestSetProcess(),
            'spine-list': mfgames_writing.opf.spine.SpineListProcess(),
            'spine-remove': mfgames_writing.opf.spine.SpineRemoveProcess(),
            'spine-set': mfgames_writing.opf.spine.SpineSetProcess(),
            'toc-get': mfgames_writing.opf.toc.TocGetProcess(),
            'toc-set': mfgames_writing.opf.toc.TocSetProcess(),
            'uid-get': mfgames_writing.opf.uid.UidGetProcess(),
            'uid-set': mfgames_writing.opf.uid.UidSetProcess(),
        })


if __name__ == "__main__":
    do_opf_tool(sys.argv[1:])
