#!/usr/bin/env python


import logging
import sys
import mfgames_tools
import mfgames_writing.docbook.count
import mfgames_writing.docbook.gather
import mfgames_writing.docbook.info
import mfgames_writing.docbook.text


def do_docbook_tool(arguments):
    mfgames_tools.run_tool(
        "Manipulate and convert DocBook 5 files.",
        arguments,
        {
            'bbcode':
                mfgames_writing.docbook.text.ConvertToBBCodeFilesProcess(),
            'count':
                mfgames_writing.docbook.count.CountProcess(),
            'creole':
                mfgames_writing.docbook.text.ConvertToCreoleFilesProcess(),
            'gather':
                mfgames_writing.docbook.gather.GatherFileProcess(),
            'subjectsets':
                mfgames_writing.docbook.info.ExtractSubjectsetsProcess(),
        })


if __name__ == "__main__":
    do_docbook_tool(sys.argv[1:])
