#!/usr/bin/env python


import argparse
import logging
import mfgames_tools
import mfgames_writing.creole
import sys


def do_creole_tool(arguments):
    mfgames_tools.run_tool(
        'Manipulate and convert Creole files.',
        arguments,
        {
            'docbook' : mfgames_writing.creole.CreoleDocbookConvertProcess(),
        })


if __name__ == "__main__":
    do_creole_tool(sys.argv[1:])
