#!/usr/bin/env python

import argparse
import logging
import sys

sys.path.append('/usr/share/mfgames-writing')
sys.path.append('/usr/local/share/mfgames-writing')

import tools
import writing.creole


def do_creole_tool(arguments):
    tools.run_tool(
        'Manipulate and convert Creole files.',
        arguments,
        {
            'docbook' : writing.creole.CreoleDocbookConvertProcess(),
        })


if __name__ == "__main__":
    do_creole_tool(sys.argv[1:])
